### ISSUE TITLE
Please add USBToolBox kext into the Kext Manager window for tracking updates in Kext Updater app.

### ISSUE THREAD

**Issue by THOMASVGTR** [MacThings/kextupdater#2]
It would be very helpful if USBToolBox kext is present on Kext Manager window. And also please make sure this kext can also be checked with other kexts while clicking check button. 

USBToolBox kext is superior for mapping USB ports on Windows and macOS.

**Comment by MacThings** [comment]
Done.

**Comment by THOMASVGTR** [comment]
Thank you so much, dev. Now update the GitHub release section with the 4.0.5 version, please.
