### ISSUE TITLE
Please add ( MacHyperVSupport.kext, CryptexFixup.kext, FeatureUnlock.kext ) into the Kext Manager window for tracking updates in Kext Updater app.

### ISSUE THREAD

**Issue by THOMASVGTR** [MacThings/kextupdater#3]
Please add ( MacHyperVSupport.kext, CryptexFixup.kext, FeatureUnlock.kext ) into the Kext Manager window for tracking updates in Kext Updater app. Please also make sure if these kexts also can be checked for updates by clicking check button for tracking updates. Also add these kexts into the kext manager window for easy downloading.

kext link:

https://github.com/acidanthera/MacHyperVSupport

https://github.com/acidanthera/CryptexFixup

https://github.com/acidanthera/FeatureUnlock

**Comment by MacThings** [comment]
Done. Please update.

**Comment by THOMASVGTR** [comment]
> Done. Please update.

Thank you dev.❤️
